
package ar.edu.ubp.das.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-16T12:41:57.446-03:00
 * Generated source version: 3.1.6
 * 
 */
 
public class ConsecionariaCXFCore_PortTypeServer{

    protected ConsecionariaCXFCore_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.edu.ubp.das.ws.ConsecionariaCXFCore();
        String address = "http://localhost:9090/ConsecionariaCXFCorePort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ConsecionariaCXFCore_PortTypeServer();
        System.out.println("Server ready..."); 
        
        /*Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);*/
    }
}
 
 