
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ar.edu.ubp.das.ws;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-16T12:41:57.458-03:00
 * Generated source version: 3.1.6
 * 
 */
public class ConsecionariaCXFCore_PortTypeClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://ws.das.ubp.edu.ar/", "ConsecionariaCXFCoreService");
        QName portName = new QName("http://ws.das.ubp.edu.ar/", "ConsecionariaCXFCorePort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/ConsecionariaCXFCorePort"); 
        ar.edu.ubp.das.ws.ConsecionariaCXFCore_PortType client = service.getPort(portName,  ar.edu.ubp.das.ws.ConsecionariaCXFCore_PortType.class);
        
        // Insert code to invoke methods on the client here
    }

}