
package ar.edu.ubp.das.ws;

import javax.jws.WebParam.Mode;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-16T12:41:57.419-03:00
 * Generated source version: 3.1.6
 * 
 */

@WebService
public interface ConsecionariaCXFCore_PortType {

    public beans.PlanBean consultarPlan(
        java.lang.Long arg0
    );

    public java.util.List<beans.PlanBean> consultarPlanes();

    public void cancelarPlan(
        beans.PlanBean arg0
    );
}
