
package ar.ubp.edu.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Feb 17 00:31:49 ART 2018
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "cancelarPlan", namespace = "http://ws.das.edu.ubp.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cancelarPlan", namespace = "http://ws.das.edu.ubp.ar/")

public class CancelarPlan {

    @XmlElement(name = "planGanador")
    private beans.PlanBean planGanador;

    public beans.PlanBean getPlanGanador() {
        return this.planGanador;
    }

    public void setPlanGanador(beans.PlanBean planGanador)  {
        this.planGanador = planGanador;
    }

}

