
package ar.ubp.edu.das.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Sat Feb 17 00:31:49 ART 2018
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "consultarPlanesResponse", namespace = "http://ws.das.edu.ubp.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "consultarPlanesResponse", namespace = "http://ws.das.edu.ubp.ar/")

public class ConsultarPlanesResponse {

    @XmlElement(name = "return")
    private java.util.List<beans.PlanBean> _return;

    public java.util.List<beans.PlanBean> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<beans.PlanBean> new_return)  {
        this._return = new_return;
    }

}

