
package ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Sun Feb 18 06:57:16 ART 2018
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "cancelarPlanResponse", namespace = "http://ws.das.edu.ubp.ar/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cancelarPlanResponse", namespace = "http://ws.das.edu.ubp.ar/")

public class CancelarPlanResponse {


}

