
package ar.ubp.edu.das.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-17T00:31:50.131-03:00
 * Generated source version: 3.1.6
 * 
 */
 
public class ConcesionariaCXFOne_PortTypeServer{

    protected ConcesionariaCXFOne_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ar.ubp.edu.das.ws.ConcesionariaCXFOne();
        String address = "http://localhost:9090/ConcesionariaCXFOnePort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new ConcesionariaCXFOne_PortTypeServer();
        System.out.println("Server ready..."); 
    }
}
 
 