
package ar.ubp.edu.das.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-17T00:52:47.132-03:00
 * Generated source version: 3.1.6
 * 
 */
public final class ConcesionariaCXFOne_ConcesionariaCXFOnePort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.das.edu.ubp.ar/", "ConcesionariaCXFOneService");

    private ConcesionariaCXFOne_ConcesionariaCXFOnePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConcesionariaCXFOneService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConcesionariaCXFOneService ss = new ConcesionariaCXFOneService(wsdlURL, SERVICE_NAME);
        ConcesionariaCXFOne port = ss.getConcesionariaCXFOnePort();  
        
        {
        System.out.println("Invoking cancelarPlan...");
        ar.ubp.edu.das.ws.PlanBean _cancelarPlan_planGanador = new ar.ubp.edu.das.ws.PlanBean();
        _cancelarPlan_planGanador.setClientId("ClientId1090983408");
        _cancelarPlan_planGanador.setConcesionaria("Concesionaria463311593");
        _cancelarPlan_planGanador.setConcesionariaId(Integer.valueOf(597559920));
        _cancelarPlan_planGanador.setCuotasPagadas(Integer.valueOf(490283267));
        _cancelarPlan_planGanador.setDocumento(Long.valueOf(6989503599266502937l));
        ar.ubp.edu.das.ws.Timestamp _cancelarPlan_planGanadorFechaAlta = new ar.ubp.edu.das.ws.Timestamp();
        _cancelarPlan_planGanadorFechaAlta.setNanos(233115556);
        _cancelarPlan_planGanador.setFechaAlta(_cancelarPlan_planGanadorFechaAlta);
        ar.ubp.edu.das.ws.Timestamp _cancelarPlan_planGanadorFechaUltimoUpdate = new ar.ubp.edu.das.ws.Timestamp();
        _cancelarPlan_planGanadorFechaUltimoUpdate.setNanos(1374098831);
        _cancelarPlan_planGanador.setFechaUltimoUpdate(_cancelarPlan_planGanadorFechaUltimoUpdate);
        _cancelarPlan_planGanador.setId(Integer.valueOf(-443018839));
        _cancelarPlan_planGanador.setVehiculo("Vehiculo1972629092");
        port.cancelarPlan(_cancelarPlan_planGanador);


        }
        {
        System.out.println("Invoking consultarPlanes...");
        java.util.List<ar.ubp.edu.das.ws.PlanBean> _consultarPlanes__return = port.consultarPlanes();
        System.out.println("consultarPlanes.result=" + _consultarPlanes__return);


        }
        {
        System.out.println("Invoking consultarPlan...");
        java.lang.Long _consultarPlan_planId = Long.valueOf(3352165802813847713l);
        ar.ubp.edu.das.ws.PlanBean _consultarPlan__return = port.consultarPlan(_consultarPlan_planId);
        System.out.println("consultarPlan.result=" + _consultarPlan__return);


        }

        System.exit(0);
    }

}
