
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ar.ubp.edu.das.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-17T00:52:47.390-03:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "ConcesionariaCXFOneService",
                      portName = "ConcesionariaCXFOnePort",
                      targetNamespace = "http://ws.das.edu.ubp.ar/",
                      wsdlLocation = "http://localhost:9090/ConcesionariaCXFOnePort?wsdl",
                      endpointInterface = "ar.ubp.edu.das.ws.ConcesionariaCXFOne")
                      
public class ConcesionariaCXFOnePortImpl implements ConcesionariaCXFOne {

    private static final Logger LOG = Logger.getLogger(ConcesionariaCXFOnePortImpl.class.getName());

    /* (non-Javadoc)
     * @see ar.ubp.edu.das.ws.ConcesionariaCXFOne#cancelarPlan(ar.ubp.edu.das.ws.PlanBean  planGanador )*
     */
    public void cancelarPlan(ar.ubp.edu.das.ws.PlanBean planGanador) { 
        LOG.info("Executing operation cancelarPlan");
        System.out.println(planGanador);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ar.ubp.edu.das.ws.ConcesionariaCXFOne#consultarPlanes(*
     */
    public java.util.List<ar.ubp.edu.das.ws.PlanBean> consultarPlanes() { 
        LOG.info("Executing operation consultarPlanes");
        try {
            java.util.List<ar.ubp.edu.das.ws.PlanBean> _return = new java.util.ArrayList<ar.ubp.edu.das.ws.PlanBean>();
            ar.ubp.edu.das.ws.PlanBean _returnVal1 = new ar.ubp.edu.das.ws.PlanBean();
            _returnVal1.setClientId("ClientId-1771935477");
            _returnVal1.setConcesionaria("Concesionaria1864177996");
            _returnVal1.setConcesionariaId(Integer.valueOf(-1139632424));
            _returnVal1.setCuotasPagadas(Integer.valueOf(-1852399824));
            _returnVal1.setDocumento(Long.valueOf(2110285337709935620l));
            ar.ubp.edu.das.ws.Timestamp _returnVal1FechaAlta = new ar.ubp.edu.das.ws.Timestamp();
            _returnVal1FechaAlta.setNanos(1425344902);
            _returnVal1.setFechaAlta(_returnVal1FechaAlta);
            ar.ubp.edu.das.ws.Timestamp _returnVal1FechaUltimoUpdate = new ar.ubp.edu.das.ws.Timestamp();
            _returnVal1FechaUltimoUpdate.setNanos(843562173);
            _returnVal1.setFechaUltimoUpdate(_returnVal1FechaUltimoUpdate);
            _returnVal1.setId(Integer.valueOf(448366519));
            _returnVal1.setVehiculo("Vehiculo1821891071");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ar.ubp.edu.das.ws.ConcesionariaCXFOne#consultarPlan(java.lang.Long  planId )*
     */
    public ar.ubp.edu.das.ws.PlanBean consultarPlan(java.lang.Long planId) { 
        LOG.info("Executing operation consultarPlan");
        System.out.println(planId);
        try {
            ar.ubp.edu.das.ws.PlanBean _return = new ar.ubp.edu.das.ws.PlanBean();
            _return.setClientId("ClientId1063380");
            _return.setConcesionaria("Concesionaria344913168");
            _return.setConcesionariaId(Integer.valueOf(-986318459));
            _return.setCuotasPagadas(Integer.valueOf(1099047619));
            _return.setDocumento(Long.valueOf(5636709105556346150l));
            ar.ubp.edu.das.ws.Timestamp _returnFechaAlta = new ar.ubp.edu.das.ws.Timestamp();
            _returnFechaAlta.setNanos(-1414908905);
            _return.setFechaAlta(_returnFechaAlta);
            ar.ubp.edu.das.ws.Timestamp _returnFechaUltimoUpdate = new ar.ubp.edu.das.ws.Timestamp();
            _returnFechaUltimoUpdate.setNanos(-862120446);
            _return.setFechaUltimoUpdate(_returnFechaUltimoUpdate);
            _return.setId(Integer.valueOf(-1811326567));
            _return.setVehiculo("Vehiculo523822953");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
