package ar.ubp.edu.das.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-17T00:52:47.481-03:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://ws.das.edu.ubp.ar/", name = "ConcesionariaCXFOne")
@XmlSeeAlso({ObjectFactory.class})
public interface ConcesionariaCXFOne {

    @WebMethod(action = "urn:CancelarPlan")
    @RequestWrapper(localName = "cancelarPlan", targetNamespace = "http://ws.das.edu.ubp.ar/", className = "ar.ubp.edu.das.ws.CancelarPlan")
    @ResponseWrapper(localName = "cancelarPlanResponse", targetNamespace = "http://ws.das.edu.ubp.ar/", className = "ar.ubp.edu.das.ws.CancelarPlanResponse")
    public void cancelarPlan(
        @WebParam(name = "planGanador", targetNamespace = "")
        ar.ubp.edu.das.ws.PlanBean planGanador
    );

    @WebMethod(action = "urn:ConsultarPlanes")
    @RequestWrapper(localName = "consultarPlanes", targetNamespace = "http://ws.das.edu.ubp.ar/", className = "ar.ubp.edu.das.ws.ConsultarPlanes")
    @ResponseWrapper(localName = "consultarPlanesResponse", targetNamespace = "http://ws.das.edu.ubp.ar/", className = "ar.ubp.edu.das.ws.ConsultarPlanesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ar.ubp.edu.das.ws.PlanBean> consultarPlanes();

    @WebMethod(action = "urn:ConsultarPlan")
    @RequestWrapper(localName = "consultarPlan", targetNamespace = "http://ws.das.edu.ubp.ar/", className = "ar.ubp.edu.das.ws.ConsultarPlan")
    @ResponseWrapper(localName = "consultarPlanResponse", targetNamespace = "http://ws.das.edu.ubp.ar/", className = "ar.ubp.edu.das.ws.ConsultarPlanResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ar.ubp.edu.das.ws.PlanBean consultarPlan(
        @WebParam(name = "planId", targetNamespace = "")
        java.lang.Long planId
    );
}
