package ar.ubp.edu.das.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-02-17T00:52:47.517-03:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "ConcesionariaCXFOneService", 
                  wsdlLocation = "http://localhost:9090/ConcesionariaCXFOnePort?wsdl",
                  targetNamespace = "http://ws.das.edu.ubp.ar/") 
public class ConcesionariaCXFOneService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.das.edu.ubp.ar/", "ConcesionariaCXFOneService");
    public final static QName ConcesionariaCXFOnePort = new QName("http://ws.das.edu.ubp.ar/", "ConcesionariaCXFOnePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9090/ConcesionariaCXFOnePort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConcesionariaCXFOneService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9090/ConcesionariaCXFOnePort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConcesionariaCXFOneService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConcesionariaCXFOneService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConcesionariaCXFOneService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ConcesionariaCXFOneService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConcesionariaCXFOneService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConcesionariaCXFOneService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ConcesionariaCXFOne
     */
    @WebEndpoint(name = "ConcesionariaCXFOnePort")
    public ConcesionariaCXFOne getConcesionariaCXFOnePort() {
        return super.getPort(ConcesionariaCXFOnePort, ConcesionariaCXFOne.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConcesionariaCXFOne
     */
    @WebEndpoint(name = "ConcesionariaCXFOnePort")
    public ConcesionariaCXFOne getConcesionariaCXFOnePort(WebServiceFeature... features) {
        return super.getPort(ConcesionariaCXFOnePort, ConcesionariaCXFOne.class, features);
    }

}
