#!/usr/bin/env bash

version: '3'
services:
  axis_one:
    image: "mssql_concesionarias:1.0"
    ports:
      - "1434:1433"
    container_name: "axis_one"
  rest_one:
    image: "mssql_concesionarias:1.0"
    ports:
      - "1435:1433"
    container_name: "rest_one"
  cxf_one:
    image: "mssql_concesionarias:1.0"
    ports:
      - "1436:1433"
    container_name: "cxf_one"
  rest_two:
    image: "mssql_concesionarias:1.0"
    ports:
      - "1437:1433"
    container_name: "rest_two"
  cxf_two:
    image: "mssql_concesionarias:1.0"
    ports:
      - "1438:1433"
    container_name: "cxf_two"


# docker-compose up -d
# docker-compose up
# docker-compose ps
# docker-compose run $service
# docker-compose stop
# docker-compose stop cxf_one rest_one cxf_two rest_two