
package service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Sat Feb 17 21:37:36 ART 2018
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "doubleItResponse", namespace = "http://www.example.org/contract/DoubleItService")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "doubleItResponse", namespace = "http://www.example.org/contract/DoubleItService")

public class DoubleItResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

