
package service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-02-17T21:37:36.603-03:00
 * Generated source version: 3.2.2
 *
 */

public class DoubleItService_PortTypeServer{

    protected DoubleItService_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new service.DoubleItService();
        String address = "http://localhost:9090/DoubleItServicePort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new DoubleItService_PortTypeServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

