
package ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2019-02-15T20:05:52.074-03:00
 * Generated source version: 3.2.2
 *
 */

public class ConcesionariaCXFTwo_PortTypeServer{

    protected ConcesionariaCXFTwo_PortTypeServer() throws Exception {
        log.debug("Starting Server");
        final Object implementor = new ws.ConcesionariaCXFTwo();
        final String address = "http://localhost:9090/ConcesionariaCXFTwoPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(final String[] args) throws Exception {
        new ConcesionariaCXFTwo_PortTypeServer();
        log.debug("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        log.debug("Server exiting");
        System.exit(0);
    }
}

